### ISSUE TITLE
Bullseye images: Operation not permitted for absolute paths

### ISSUE THREAD

**Issue by iGEL** [Quantisan/docker-clojure#123]
It seems like the bullseye images are broken:

```
circleci@adc2ca5fc6f8:~/project$ docker run -ti clojure ls /tmp
Unable to find image 'clojure:latest' locally
latest: Pulling from library/clojure
f8416d8bac72: Pull complete
86ae0b0c4c13: Pull complete
613e763baa52: Pull complete
eb9a550ef812: Pull complete
096f816168e4: Pull complete
3cbee8b8af15: Pull complete
1aca2e854b4e: Pull complete
858ad2a9d1cd: Pull complete
1604e82c84ee: Pull complete
Digest: sha256:b68af4b6c8c3c234eb4863c1ca97f2c2790700142a018341b78add9f3ed295d9
Status: Downloaded newer image for clojure:latest
ls: cannot access '/tmp': Operation not permitted

circleci@adc2ca5fc6f8:~/project$ docker run clojure ls
hsperfdata_root
linux-install-1.10.3.967.sh
target
circleci@adc2ca5fc6f8:~/project$ docker run clojure pwd
/tmp
```

Same for other paths, I tried `/` and `/usr`. Buster seems to be fine.

**Comment by cap10morgan** [comment]
OK I’ll look into it

**Comment by iGEL** [comment]
Thank you! If I can help somehow, please let me know.

**Comment by cap10morgan** [comment]
I am unable to reproduce this. Can you give me any more info / context, @iGEL?

**Comment by iGEL** [comment]
Right, I was not able to reproduce this outside of CircleCI, even with a remote docker in a virtual machine.

If you want, here a `.circleci/config.yml` to demonstrate:
```yml
version: 2
jobs:
  clojure_docker:
    resource_class: small
    docker:
      - image: cimg/ruby:3.0
    steps:
      - setup_remote_docker
      - run: docker run clojure ls /tmp

workflows:
  version: 2
  test:
    jobs:
      - clojure_docker
```

Possibly it's related to their docker version (17.09.0-ce)?

But I'm fine if you close this bug, even though it was working yesterday and I was able to reproduce it with several bullseye images.

**Comment by cap10morgan** [comment]
Yeah that sounds like a CircleCI issue. I would contact them about it. If they trace it to something we need to change in this image, please open a new issue w/ the relevant details. Thanks and good luck!

**Comment by iGEL** [comment]
The last guess was correct, it seems to be the docker version. This passes:

```yml
version: 2
jobs:
  clojure_docker:
    resource_class: small
    docker:
      - image: cimg/ruby:3.0
    steps:
      - setup_remote_docker:
          version: 20.10.7 # <-- Fix
      - run: docker run clojure ls /tmp

workflows:
  version: 2
  test:
    jobs:
      - clojure_docker
```

Thank you for investigating and providing these images.
